git-commit-filetree: print error message when an unexpected error occurs.

diff --git a/git-commit-filetree b/git-commit-filetree
--- a/git-commit-filetree
+++ b/git-commit-filetree
@@ -1,13 +1,17 @@
 #!/bin/bash
 set -e
 
+internal_error=true
+trap '$internal_error && err "INTERNAL ERROR. FAILED!"' 0
+
 usage="Usage: git commit-filetree <branch> <path>"
 [ -z "$2" ] && {
     echo 1>&2 "$usage"
+    internal_error=false
     exit 129
 }
 
-err() { echo "$@"; exit 1; }
+err() { internal_error=false; echo "$@"; exit 1; }
 
 # Check that we have no uncommited or unknown files.
 git diff-index --quiet HEAD \
@@ -15,4 +19,5 @@ git diff-index --quiet HEAD \
 [ -z "$(git ls-files --exclude-standard --others)" ] \
     || err "Cannot commit with untracked files in working copy."
 
+internal_error=false
 exit 0
